package org.smartregister.chw.interactor;

import org.smartregister.chw.core.interactor.CorePncMedicalHistoryActivityInteractor;

public class PncMedicalHistoryActivityInteractor extends CorePncMedicalHistoryActivityInteractor{}