indicators:
  - key: "pnc_report_indicator_1_1"
    description: "COUNT of women who delivered in a health facility (last 6 months)"
    indicatorQuery: "select count(*) from ec_pregnancy_outcome where (preg_outcome = 'Live birth' or preg_outcome = 'Stillbirth') and delivery_place = 'Health facility' and delivery_date >= date('now', '-6 month')"

  - key: "pnc_report_indicator_1_2"
    description: "COUNT of women who delivered elsewhere (last 6 months)"
    indicatorQuery: "select count(*) from ec_pregnancy_outcome where (preg_outcome = 'Live birth' or preg_outcome = 'Stillbirth') and (delivery_place = 'Home' or delivery_place = 'Other') and delivery_date >= date('now', '-6 month')"

  - key: "pnc_report_indicator_2_1"
    description: "COUNT of babies born with normal birth weight (last 6 months)"
    indicatorQuery: "select count(*) from ec_child where ec_child.low_birth_weight = 'No' and ec_child.dob >= date('now', '-6 month') and ec_child.dod ISNULL and ec_child.relational_id in (select ec_pregnancy_outcome.relational_id from ec_pregnancy_outcome where ec_pregnancy_outcome.preg_outcome = 'Live birth' and ec_pregnancy_outcome.delivery_date >= date('now', '-6 month'));"

  - key: "pnc_report_indicator_2_2"
    description: "COUNT of babies born with low birth weight"
    indicatorQuery: "select count(*) from ec_child where ec_child.low_birth_weight = 'Yes' and ec_child.dob >= date('now', '-6 month') and ec_child.dod ISNULL and ec_child.relational_id in (select ec_pregnancy_outcome.relational_id from ec_pregnancy_outcome where ec_pregnancy_outcome.preg_outcome = 'Live birth' and ec_pregnancy_outcome.delivery_date >= date('now', '-6 month'));"

  - key: "pnc_report_indicator_3_1"
    description: "COUNT of babies born who were early initiated into breastfeeding (last 6 months)"
    indicatorQuery: "select count(*) from ec_child where ec_child.early_bf_1hr = 'Yes' and ec_child.dob >= date('now', '-6 month') and ec_child.dod ISNULL and ec_child.relational_id in (select ec_pregnancy_outcome.relational_id from ec_pregnancy_outcome where ec_pregnancy_outcome.preg_outcome = 'Live birth' and ec_pregnancy_outcome.delivery_date >= date('now', '-6 month'));"

  - key: "pnc_report_indicator_3_2"
    description: "COUNT of babies born who were not early initiated into breastfeeding"
    indicatorQuery: "select count(*) from ec_child where ec_child.early_bf_1hr = 'No' and ec_child.dob >= date('now', '-6 month') and ec_child.dod ISNULL and ec_child.relational_id in (select ec_pregnancy_outcome.relational_id from ec_pregnancy_outcome where ec_pregnancy_outcome.preg_outcome = 'Live birth' and ec_pregnancy_outcome.delivery_date >= date('now', '-6 month'));"
